name: jdoodle
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  webview_flutter: ^4.9.0 # For Monaco Editor integration
  shared_preferences: ^2.3.2
  uuid: ^4.5.0 # To generate unique IDs for saved programs
  web_socket_channel: ^3.0.1
  html: ^0.15.4
  dropdown_button2: ^2.3.9
  custom_radio_grouped_button: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

